- name: Set vars
  ansible.builtin.set_fact:
    answer: "10.{{ range_second_octet }}.{{ (ludus | selectattr('vm_name', 'match', vm_name) | first).vlan }}.{{ (ludus | selectattr('vm_name', 'match', vm_name) | first).ip_last_octet }}"
    rewrites: "{{ (ludus | selectattr('vm_name', 'match', vm_name) | first).dns_rewrites }}"

- name: Add custom DNS rewrite rule
  ansible.builtin.uri:
    url: http://127.0.0.1:3000/control/rewrite/add
    method: POST
    status_code: [200, 202]
    return_content: true
    body_format: json
    headers:
      Authorization: Basic YWRtaW46cGFzc3dvcmQ=
    body:
      domain: "{{ domain_name }}"
      answer: "{{ answer }}"
  loop: "{{ rewrites }}"
  loop_control:
    loop_var: domain_name
